### PR TITLE
Renamed CONTRIB.md and linked it in README.md

### PR DESCRIPTION
**Pull request by dellagustin**
Solves #184

### CODE REVIEW

**Comment by dellagustin** [comment]
Despite the check failure, my CLA is signed:
image

**Comment by dellagustin** [comment]
I re-signed the CLA with the same email I used to author the commits on the pull request.

**Comment by nic0lette** [comment]
Hey @googlebot ! Can you check again please?

**Comment by grant** [comment]
@dellagustin It looks like you used a different email in the commit than the one you used signing the CLA. You can see in this PR that the commit doesn't show your profile image next to it.

Try adding the email (dellagutin@) to your GitHub account or sign the commit with a different email. Then say "I signed it!"

**Pull request closed without merging**
