### PR TITLE
Optimized image files

### PR DESCRIPTION
**Pull request by konifar**
Some icons were not optimized.
So I optimized icons by using [ImageOptim](https://imageoptim.com/).

After optimized, the icons size are reduced 31.3% on average.

imageoptim

### CODE REVIEW

**Comment by konifar** [comment]
Could you review it? :bow:

**Comment by aungaungsoe10** [comment]
Why?

**Comment by konifar** [comment]
@aungaungsoe10 What do you mean?

**Comment by aungaungsoe10** [comment]
Leave

**Comment by dgadelha** [comment]
It compressed the images. It's a bad idea to do that.

My suggestion is: try out the **SteelBytes JPG/PNG Stripper**, it removes *only* metadata - without compression.

Plus, you only saved 108 KB with compressions. I don't know you, but I'd rather make my app 108 KB bigger and have full quality icons than compressing them.

**Comment by nic0lette** [comment]
Thank you for your contribution, but since we've mostly switched to using vector drawables, and the fact that there was the complete rewrite, I'm going to just close this PR.

**Pull request closed without merging**
