### PR TITLE
fixed notification state bug.

### PR DESCRIPTION
**Pull request by huangyanan**
first start to play music, the notification's play state was wrong.when the music start play, the notification first is "pause" state and it was right ,but then it refresh to "start" state.because the fetchBitmapFromURLAsync method refresh notification with old Notification builder.

### CODE REVIEW

**Comment by huangyanan** [comment]
I signed it!

**Comment by huangyanan** [comment]
I signed it!

**Comment by huangyanan** [comment]
I signed it!

**Comment by nic0lette** [comment]
Thanks for your contribution, but given the conflict and not being able to find a CLA, I'm going to close this PR.

**Pull request closed without merging**
